# Rhis is second demo workflow

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

  
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: deploy
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script v2
        run: |
          echo Add other actions to build, v2
          echo test, and deploy your project. v2
